version: 1
accounts:
- name: test1
  coins:
  - 20000000000uboard
  mnemonic: slogan wreck armor floor change female industry smart daughter spawn today
    system shop pigeon game olive always dish camp response can perfect salon stone
- name: test2
  coins:
  - 20000000000uboard
  mnemonic: boil silk digital carry photo explain kitchen wall unusual garlic suspect
    leave accident discover banana catch margin reward gap asset raccoon anchor leisure
    ostrich
- name: test3
  coins:
  - 240000000000uboard
  mnemonic: bounce duty afraid make item occur curious mention stamp lava inspire
    shock wall hungry culture apart harsh icon burden glide cabbage deal during charge
- name: alice
  coins:
  - 990000000000000uboard
  mnemonic: satisfy dirt consider electric apart coin later recall enhance pizza dust
    way shop erosion innocent actor member double always budget rival congress person
    uncle
- name: bob
  coins:
  - 91000000000000uboard
  mnemonic: address slogan history guitar fringe health coral dish exercise excite
    utility now thank mosquito soul vacuum doctor squeeze host never dinosaur afford
    tide tide
- name: prod1
  coins:
  - 20000000000uboard
  mnemonic: thing lamp dwarf pupil hundred harsh snack review chest pledge people
    normal pattern shoe cereal drill staff people finger type timber buddy grab rate
- name: prod2
  coins:
  - 200000000000uboard
  mnemonic: invest theme among elbow weekend couple erode oyster stand enjoy series
    collect ripple fringe actual muscle idle vast heavy brass donkey minimum envelope
    capable
faucet:
  name: bob
  coins:
  - 1000000000uboard
  host: 0.0.0.0:4500
genesis: 
  app_state:
    crisis:
      constant_fee:
        amount: "10"
        denom: uboard
    gov:
      deposit_params:
        min_deposit:
          amount: "10"
          denom: uboard
    mint:
      params:
        mint_denom: uboard
    staking:
      params:
        bond_denom: uboard
  bank:
    denom_metadata: null
    denom_units:
      denom: uboard
      exponent: "6"
      aliases: microboard
      denom: board
      exponent: "0"
    description: The native staking token of surfboard blockchain
    base: uboard
    display: board
    name: board
    symbol: BOARD
  chain_id: board-testnet-0
validators:
- name: alice
  bonded: 10000000000uboard
  home: $HOME/.board 
